name: Issue
on: [issues, issue_comment]

jobs:
  issues:
    name: Action
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/actions@master
        name: "Running HACS Actions"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
