name: Pull request
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened, closed]

jobs:
  pull_request:
    name: Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint datafiles with JQ
        run: |
            jq --raw-output "." "appdaemon"
            jq --raw-output "." "blacklist"
            jq --raw-output "." "integration"
            jq --raw-output "." "plugin"
            jq --raw-output "." "python_script"
            jq --raw-output "." "theme"
      - uses: hacs/actions@master
        name: "Running HACS Actions"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"